from typing import override

from pydantic import RootModel

# --- String-based aliases (from PrimStr) --------------------------------------

class MetricName(RootModel[str]):
    root: str
    def __len__(self) -> int: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: MetricName | str) -> bool: ...
    def __le__(self, other: MetricName | str) -> bool: ...
    def __gt__(self, other: MetricName | str) -> bool: ...
    def __ge__(self, other: MetricName | str) -> bool: ...

class MetricLabelKey(RootModel[str]):
    root: str
    def __len__(self) -> int: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...

class MetricLabelValue(RootModel[str]):
    root: str
    def __len__(self) -> int: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...

# --- Numeric aliases ----------------------------------------------------------

class MetricValue(RootModel[float]):
    root: float
    def __add__(self, other: MetricValue | float) -> MetricValue: ...
    def __sub__(self, other: MetricValue | float) -> MetricValue: ...
    def __mul__(self, other: MetricValue | float) -> MetricValue: ...
    def __truediv__(self, other: MetricValue | float) -> MetricValue: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: MetricValue | float) -> bool: ...
    def __le__(self, other: MetricValue | float) -> bool: ...
    def __gt__(self, other: MetricValue | float) -> bool: ...
    def __ge__(self, other: MetricValue | float) -> bool: ...
