def mi_visit(code: str, multi: bool = True) -> float: ...
def mi_rank(mi: float) -> str: ...
def mi_parameters(code: str, count_multi: bool = True) -> dict[str, float]: ...

__all__ = ["mi_parameters", "mi_rank", "mi_visit"]
