from typing import Generic, TypeVar

K = TypeVar("K")
V = TypeVar("V")

class BaseCacheImpl(Generic[K, V]):  # noqa: UP046
    def get(self, key: K, default: V | None = None) -> V | None: ...
    def insert(self, key: K, value: V) -> None: ...
    def pop(self, key: K, default: V | None = None) -> V | None: ...
    def clear(self) -> None: ...
    def __contains__(self, key: K) -> bool: ...

class LRUCache(BaseCacheImpl[K, V]):
    def __init__(self, maxsize: int) -> None: ...

class LFUCache(BaseCacheImpl[K, V]):
    def __init__(self, maxsize: int) -> None: ...

class FIFOCache(BaseCacheImpl[K, V]):
    def __init__(self, maxsize: int) -> None: ...

class TTLCache(BaseCacheImpl[K, V]):
    def __init__(self, maxsize: int, ttl: int) -> None: ...
    def insert_with_ttl(self, key: K, value: V, ttl: int) -> None: ...

__all__ = [
    "BaseCacheImpl",
    "FIFOCache",
    "LFUCache",
    "LRUCache",
    "TTLCache",
]
