from typing import Any

class DiskBackend:
    def __init__(self, cache_dir: str = ".aiocache") -> None: ...
    async def get(self, key: str, default: Any = None) -> Any: ...  # noqa: ANN401
    async def set(self, key: str, value: Any, ttl: int | None = None) -> bool: ...  # noqa: ANN401
    async def delete(self, key: str) -> bool: ...
    async def exists(self, key: str) -> bool: ...
    async def clear(self) -> None: ...
    async def multi_get(self, keys: list[str]) -> list[Any]: ...
    async def multi_set(self, pairs: list[tuple[str, Any]], ttl: int | None = None) -> bool: ...
