# .github/workflows/ci.yml
name: Continuous Integration

on:
    pull_request:
        branches: ["master"]

jobs:
    test-and-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install Nox
              run: pipx install nox

            - name: Run Nox Sessions
              run: nox -s lint mypy pre_commit tests
