# .github/workflows/release.yml
name: Create and Publish Release

on:
    push:
        branches:
            - master

jobs:
    test: # New job to run tests first
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install Nox
              run: pipx install nox

            - name: Run tests
              env:
                  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
              run: nox -s tests

    release:
        needs: test # This job will only run if the 'test' job succeeds
        runs-on: ubuntu-latest
        permissions:
            contents: write # Needed to push new commits and tags
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetches all history for semantic-release

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install Nox
              run: pipx install nox

            - name: Run Semantic Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the built-in, more secure token
              run: nox -s release
